version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli

  build:
    commands:
      - echo "Building Angular SSR application..."
      - npm run build:ssr

      - echo "Preparing Elastic Beanstalk deployment bundle..."

      - mkdir -p deploy

      - cp -R dist/portfolio/* deploy/

      - echo "import('./server/server.mjs');" > deploy/server.js

      - cp package.json deploy/

      - sed -i 's#"serve:ssr": .*#"start": "node server.js",#' deploy/package.json

artifacts:
  base-directory: deploy
  files:
    - "**/*"