version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - npm install -g @angular/cli

  build:
    commands:
      - echo "Building Angular SSR application..."
      - npm run build:ssr

post_build:
  commands:
    - echo "Preparing Elastic Beanstalk deployment bundle..."
    - mkdir -p deploy
    - cp -R dist/portfolio/browser deploy/public
    - cp -R dist/portfolio/server deploy/server
    - cp Procfile deploy/
    - cd deploy
    - zip -r ../build-output.zip .
artifacts:
  files:
    - build-output.zip