version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - npm install -g @angular/cli

  build:
    commands:
      - echo "Building Angular SSR application..."
      - npm run build:ssr

  post_build:
    commands:
      - echo "Preparing Elastic Beanstalk deployment bundle..."
      - mkdir -p deploy
      - cp -R dist/portfolio/browser deploy/public
      - cp -R dist/portfolio/server deploy/server
      - cp server.ts deploy/
      - cd deploy
      - npx tsc server.ts --esModuleInterop --module commonjs --target es2017
      - rm server.ts

artifacts:
  files:
    - '**/*'
  base-directory: deploy