version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli

  build:
    commands:
      - echo "Building Angular SSR application..."
      - npm run build:ssr || npm run build:prod
      - echo "Preparing Elastic Beanstalk deployment bundle..."
      - mkdir -p deploy
      - cp -R dist/portfolio/* deploy/
      - echo "import('./server/server.mjs');" > deploy/server.js
      - cp package.json deploy/
      - |
        node -e "const fs=require('fs'); const p='./deploy/package.json'; const j=JSON.parse(fs.readFileSync(p)); j.scripts={ start: 'node server.js' }; fs.writeFileSync(p, JSON.stringify(j, null, 2));"

artifacts:
  base-directory: deploy
  files:
    - "**/*"